
import { Pokemon } from '../types';

// 第一、二、三世代宝可梦的中文名映射（没在表里的就显示英文名）
// 作为“白名单覆盖”，其余世代优先从 PokeAPI 的中文本地化名称里自动获取
const CHINESE_NAME_MAP: Record<string, string> = {
  // Gen 1
  "bulbasaur": "妙蛙种子",
  "ivysaur": "妙蛙草",
  "venusaur": "妙蛙花",
  "charmander": "小火龙",
  "charmeleon": "火恐龙",
  "charizard": "喷火龙",
  "squirtle": "杰尼龟",
  "wartortle": "卡咪龟",
  "blastoise": "水箭龟",
  "caterpie": "绿毛虫",
  "metapod": "铁甲蛹",
  "butterfree": "巴大蝶",
  "weedle": "独角虫",
  "kakuna": "铁壳蛹",
  "beedrill": "大针蜂",
  "pidgey": "波波",
  "pidgeotto": "比比鸟",
  "pidgeot": "大比鸟",
  "rattata": "小拉达",
  "raticate": "拉达",
  "spearow": "烈雀",
  "fearow": "大嘴雀",
  "ekans": "阿柏蛇",
  "arbok": "阿柏怪",
  "pikachu": "皮卡丘",
  "raichu": "雷丘",
  "sandshrew": "穿山鼠",
  "sandslash": "穿山王",
  "nidoran-f": "尼多兰",
  "nidorina": "尼多娜",
  "nidoqueen": "尼多后",
  "nidoran-m": "尼多朗",
  "nidorino": "尼多力诺",
  "nidoking": "尼多王",
  "clefairy": "皮皮",
  "clefable": "皮可西",
  "vulpix": "六尾",
  "ninetales": "九尾",
  "jigglypuff": "胖丁",
  "wigglytuff": "胖可丁",
  "zubat": "超音蝠",
  "golbat": "大嘴蝠",
  "oddish": "走路草",
  "gloom": "臭臭花",
  "vileplume": "霸王花",
  "paras": "派拉斯",
  "parasect": "派拉斯特",
  "venonat": "毛球",
  "venomoth": "摩鲁蛾",
  "diglett": "地鼠",
  "dugtrio": "三地鼠",
  "meowth": "喵喵",
  "persian": "猫老大",
  "psyduck": "可达鸭",
  "golduck": "哥达鸭",
  "mankey": "猴怪",
  "primeape": "火暴猴",
  "growlithe": "卡蒂狗",
  "arcanine": "风速狗",
  "poliwag": "蚊香蝌蚪",
  "poliwhirl": "蚊香君",
  "poliwrath": "蚊香泳士",
  "abra": "凯西",
  "kadabra": "勇基拉",
  "alakazam": "胡地",
  "machop": "腕力",
  "machoke": "豪力",
  "machamp": "怪力",
  "bellsprout": "喇叭芽",
  "weepinbell": "口呆花",
  "victreebel": "大食花",
  "tentacool": "玛瑙水母",
  "tentacruel": "毒刺水母",
  "geodude": "小拳石",
  "graveler": "隆隆石",
  "golem": "隆隆岩",
  "ponyta": "小火马",
  "rapidash": "烈焰马",
  "slowpoke": "呆呆兽",
  "slowbro": "呆壳兽",
  "magnemite": "小磁怪",
  "magneton": "三合一磁怪",
  "farfetchd": "大葱鸭",
  "doduo": "嘟嘟",
  "dodrio": "嘟嘟利",
  "seel": "小海狮",
  "dewgong": "白海狮",
  "grimer": "臭泥",
  "muk": "臭臭泥",
  "shellder": "大舌贝",
  "cloyster": "刺甲贝",
  "gastly": "鬼斯",
  "haunter": "鬼斯通",
  "gengar": "耿鬼",
  "onix": "大岩蛇",
  "drowzee": "催眠貘",
  "hypno": "引梦貘人",
  "krabby": "大钳蟹",
  "kingler": "巨钳蟹",
  "voltorb": "霹雳电球",
  "electrode": "顽皮雷弹",
  "exeggcute": "蛋蛋",
  "exeggutor": "椰蛋树",
  "cubone": "卡拉卡拉",
  "marowak": "嘎啦嘎啦",
  "hitmonlee": "飞腿郎",
  "hitmonchan": "快拳郎",
  "lickitung": "大舌头",
  "koffing": "瓦斯弹",
  "weezing": "双弹瓦斯",
  "rhyhorn": "独角犀牛",
  "rhydon": "钻角犀兽",
  "chansey": "吉利蛋",
  "tangela": "蔓藤怪",
  "kangaskhan": "袋兽",
  "horsea": "墨海马",
  "seadra": "海刺龙",
  "goldeen": "角金鱼",
  "seaking": "金鱼王",
  "staryu": "海星星",
  "starmie": "宝石海星",
  "mr-mime": "魔墙人偶",
  "scyther": "飞天螳螂",
  "jynx": "迷唇姐",
  "electabuzz": "电击兽",
  "magmar": "鸭嘴火兽",
  "pinsir": "凯罗斯",
  "tauros": "肯泰罗",
  "magikarp": "鲤鱼王",
  "gyarados": "暴鲤龙",
  "lapras": "拉普拉斯",
  "ditto": "百变怪",
  "eevee": "伊布",
  "vaporeon": "水伊布",
  "jolteon": "雷伊布",
  "flareon": "火伊布",
  "porygon": "多边兽",
  "omanyte": "菊石兽",
  "omastar": "多刺菊石兽",
  "kabuto": "化石盔",
  "kabutops": "镰刀盔",
  "aerodactyl": "化石翼龙",
  "snorlax": "卡比兽",
  "articuno": "急冻鸟",
  "zapdos": "闪电鸟",
  "moltres": "火焰鸟",
  "dratini": "迷你龙",
  "dragonair": "哈克龙",
  "dragonite": "快龙",
  "mewtwo": "超梦",
  "mew": "梦幻",

  // Gen 2
  "chikorita": "菊草叶",
  "bayleef": "月桂叶",
  "meganium": "大竺葵",
  "cyndaquil": "火球鼠",
  "quilava": "火岩鼠",
  "typhlosion": "火暴兽",
  "totodile": "小锯鳄",
  "croconaw": "蓝鳄",
  "feraligatr": "大力鳄",
  "sentret": "尾立",
  "furret": "大尾立",
  "hoothoot": "咕咕",
  "noctowl": "猫头夜鹰",
  "ledyba": "芭瓢虫",
  "ledian": "安瓢虫",
  "spinarak": "圆丝蛛",
  "ariados": "阿利多斯",
  "crobat": "叉字蝠",
  "chinchou": "灯笼鱼",
  "lanturn": "电灯怪",
  "pichu": "皮丘",
  "cleffa": "皮宝宝",
  "igglybuff": "宝宝丁",
  "togepi": "波克比",
  "togetic": "波克基古",
  "natu": "天然雀",
  "xatu": "天然鸟",
  "mareep": "咩利羊",
  "flaaffy": "茸茸羊",
  "ampharos": "电龙",
  "bellossom": "美丽花",
  "marill": "玛力露",
  "azumarill": "玛力露丽",
  "sudowoodo": "树才怪",
  "politoed": "蚊香蛙皇",
  "hoppip": "毽子草",
  "skiploom": "毽子花",
  "jumpluff": "毽子棉",
  "aipom": "长尾怪手",
  "sunkern": "向日种子",
  "sunflora": "向日花怪",
  "yanma": "蜻蜻蜓",
  "wooper": "乌波",
  "quagsire": "沼王",
  "espeon": "太阳伊布",
  "umbreon": "月亮伊布",
  "murkrow": "黑暗鸦",
  "slowking": "呆呆王",
  "misdreavus": "梦妖",
  "unown": "未知图腾",
  "wobbuffet": "果然翁",
  "girafarig": "麒麟奇",
  "pineco": "榛果球",
  "forretress": "佛烈托斯",
  "dunsparce": "土龙弟弟",
  "gligar": "天蝎",
  "steelix": "大钢蛇",
  "snubbull": "布鲁",
  "granbull": "布鲁皇",
  "qwilfish": "千针鱼",
  "scizor": "巨钳螳螂",
  "shuckle": "壶壶",
  "heracross": "赫拉克罗斯",
  "sneasel": "狃拉",
  "teddiursa": "熊宝宝",
  "ursaring": "圈圈熊",
  "slugma": "熔岩虫",
  "magcargo": "熔岩蜗牛",
  "swinub": "小山猪",
  "piloswine": "长毛猪",
  "corsola": "太阳珊瑚",
  "remoraid": "铁炮鱼",
  "octillery": "章鱼桶",
  "delibird": "信使鸟",
  "mantine": "巨翅飞鱼",
  "skarmory": "盔甲鸟",
  "houndour": "戴鲁比",
  "houndoom": "黑鲁加",
  "kingdra": "刺龙王",
  "phanpy": "小小象",
  "donphan": "顿甲",
  "porygon2": "多边兽２型",
  "stantler": "惊角鹿",
  "smeargle": "图图犬",
  "tyrogue": "无畏小子",
  "hitmontop": "战舞郎",
  "smoochum": "迷唇娃",
  "elekid": "电击怪",
  "magby": "鸭嘴宝宝",
  "miltank": "大奶罐",
  "blissey": "幸福蛋",
  "raikou": "雷公",
  "entei": "炎帝",
  "suicune": "水君",
  "larvitar": "幼基拉斯",
  "pupitar": "沙基拉斯",
  "tyranitar": "班基拉斯",
  "lugia": "洛奇亚",
  "ho-oh": "凤王",
  "celebi": "时拉比",

  // Gen 3（仅补你列出的 #252–#386）
  "treecko": "木守宫",
  "grovyle": "森林蜥蜴",
  "sceptile": "蜥蜴王",
  "torchic": "火稚鸡",
  "combusken": "力壮鸡",
  "blaziken": "火焰鸡",
  "mudkip": "水跃鱼",
  "marshtomp": "沼跃鱼",
  "swampert": "巨沼怪",
  "poochyena": "土狼犬",
  "mightyena": "大狼犬",
  "zigzagoon": "蛇纹熊",
  "linoone": "直冲熊",
  "wurmple": "刺尾虫",
  "silcoon": "甲壳茧",
  "beautifly": "狩猎凤蝶",
  "cascoon": "盾甲茧",
  "dustox": "毒粉蛾",
  "lotad": "莲叶童子",
  "lombre": "莲帽小童",
  "ludicolo": "乐天河童",
  "seedot": "橡实果",
  "nuzleaf": "长鼻叶",
  "shiftry": "狡猾天狗",
  "taillow": "傲骨燕",
  "swellow": "大王燕",
  "wingull": "长翅鸥",
  "pelipper": "大嘴鸥",
  "ralts": "拉鲁拉丝",
  "kirlia": "奇鲁莉安",
  "gardevoir": "沙奈朵",
  "surskit": "溜溜糖球",
  "masquerain": "雨翅蛾",
  "shroomish": "蘑蘑菇",
  "breloom": "斗笠菇",
  "slakoth": "懒人獭",
  "vigoroth": "过动猿",
  "slaking": "请假王",
  "nincada": "土居忍士",
  "ninjask": "铁面忍者",
  "shedinja": "脱壳忍者",
  "whismur": "咕妞妞",
  "loudred": "吼爆弹",
  "exploud": "爆音怪",
  "makuhita": "幕下力士",
  "hariyama": "铁掌力士",
  "azurill": "露力丽",
  "nosepass": "朝北鼻",
  "skitty": "向尾喵",
  "delcatty": "优雅猫",
  "sableye": "勾魂眼",
  "mawile": "大嘴娃",
  "aron": "可可多拉",
  "lairon": "可多拉",
  "aggron": "波士可多拉",
  "meditite": "玛沙那",
  "medicham": "恰雷姆",
  "electrike": "落雷兽",
  "manectric": "雷电兽",
  "plusle": "正电拍拍",
  "minun": "负电拍拍",
  "volbeat": "电萤虫",
  "illumise": "甜甜萤",
  "roselia": "毒蔷薇",
  "gulpin": "溶食兽",
  "swalot": "吞食兽",
  "carvanha": "利牙鱼",
  "sharpedo": "巨牙鲨",
  "wailmer": "吼吼鲸",
  "wailord": "吼鲸王",
  "numel": "呆火驼",
  "camerupt": "喷火驼",
  "torkoal": "煤炭龟",
  "spoink": "跳跳猪",
  "grumpig": "噗噗猪",
  "spinda": "晃晃斑",
  "trapinch": "大颚蚁",
  "vibrava": "超音波幼虫",
  "flygon": "沙漠蜻蜓",
  "cacnea": "刺球仙人掌",
  "cacturne": "梦歌仙人掌",
  "swablu": "青绵鸟",
  "altaria": "七夕青鸟",
  "zangoose": "猫鼬斩",
  "seviper": "饭匙蛇",
  "lunatone": "月石",
  "solrock": "太阳岩",
  "barboach": "泥泥鳅",
  "whiscash": "鲶鱼王",
  "corphish": "龙虾小兵",
  "crawdaunt": "铁螯龙虾",
  "baltoy": "天秤偶",
  "claydol": "念力土偶",
  "lileep": "触手百合",
  "cradily": "摇篮百合",
  "anorith": "太古羽虫",
  "armaldo": "太古盔甲",
  "feebas": "丑丑鱼",
  "milotic": "美纳斯",
  "castform": "飘浮泡泡",
  "kecleon": "变隐龙",
  "shuppet": "怨影娃娃",
  "banette": "诅咒娃娃",
  "duskull": "夜巡灵",
  "dusclops": "彷徨夜灵",
  "tropius": "热带龙",
  "chimecho": "风铃铃",
  "absol": "阿勃梭鲁",
  "wynaut": "小果然",
  "snorunt": "雪童子",
  "glalie": "冰鬼护",
  "spheal": "海豹球",
  "sealeo": "海魔狮",
  "walrein": "帝牙海狮",
  "clamperl": "珍珠贝",
  "huntail": "猎斑鱼",
  "gorebyss": "樱花鱼",
  "relicanth": "古空棘鱼",
  "luvdisc": "爱心鱼",
  "bagon": "宝贝龙",
  "shelgon": "甲壳龙",
  "salamence": "暴飞龙",
  "beldum": "铁哑铃",
  "metang": "金属怪",
  "metagross": "巨金怪",
  "regirock": "雷吉洛克",
  "regice": "雷吉艾斯",
  "registeel": "雷吉斯奇鲁",
  "latias": "拉帝亚斯",
  "latios": "拉帝欧斯",
  "kyogre": "盖欧卡",
  "groudon": "固拉多",
  "rayquaza": "烈空坐",
  "jirachi": "基拉祈",
  "deoxys": "代欧奇希斯"
};

// 当前 PokeAPI 已收录到第九世代，图鉴 ID 约到 1010
const MAX_DEX_ID = 1010;

export const getRandomPokemon = async (): Promise<Pokemon> => {
  // 1 ~ MAX_DEX_ID 之间随机一个图鉴编号
  const randomId = Math.floor(Math.random() * MAX_DEX_ID) + 1;
  try {
    // 1. 基础信息（英文名、图片等）
    const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${randomId}`);
    const data = await res.json();
    
    const englishName: string = data.name;

    // 2. 先尝试用手动映射表里的中文名
    let chineseName: string | undefined = CHINESE_NAME_MAP[englishName];

    // 3. 如果没有手动映射，则从 species 接口里读取官方中文名
    if (!chineseName) {
      try {
        const speciesRes = await fetch(`https://pokeapi.co/api/v2/pokemon-species/${data.id}`);
        const speciesData = await speciesRes.json();
        const zhEntry =
          speciesData.names?.find((n: any) => n.language?.name === 'zh-Hans') ||
          speciesData.names?.find((n: any) => n.language?.name === 'zh-Hant') ||
          speciesData.names?.find((n: any) => n.language?.name === 'zh-TW') ||
          speciesData.names?.find((n: any) => n.language?.name === 'zh-CN');

        if (zhEntry && typeof zhEntry.name === 'string') {
          chineseName = zhEntry.name;
        }
      } catch (e) {
        // 如果物种信息获取失败，就退回英文名 / 手动表
        console.warn('Failed to fetch pokemon species info for Chinese name:', e);
      }
    }

    if (!chineseName) {
      chineseName = englishName;
    }
    
    return {
      id: data.id,
      name: englishName,
      chineseName,
      imageUrl: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${data.id}.png`
    };
  } catch (error) {
    console.error("Error fetching pokemon:", error);
    // Fallback to Pikachu
    return {
      id: 25,
      name: "pikachu",
      chineseName: "皮卡丘",
      imageUrl: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png"
    };
  }
};
